language: node_js
node_js:
  - "8.1.3"
  - "8.1.2"
  - "8.1.1"
  - "6.11.0"
  - "6.10.3"
  - "6.10.2"
before_install:
  - npm install -g yarn
install:
  - yarn
script: npm test # Defined in the package.json (scripts > test)
cache:
  directories:
    - node_modules
os:
  - osx
  - linux
