language: node_js
node_js:
  - "8"
  - "6"
before_install:
  - npm install -g -p yarn@1
install:
  - yarn
script: npm test # Defined in the package.json (scripts > test)
cache:
  directories:
    - node_modules
os:
  - osx
  - linux
