environment:
  matrix:
    - nodejs_version: '14'
    - nodejs_version: '12'
platform:
    - x86
    - x64
init:
    - git config --global core.autocrlf true
    - ps: Install-Product node $env:nodejs_version $env:platform
install:
    - npm install
build: off
test_script:
  - npm test # Defined in the package.json (scripts > test)
