version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build_test:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - run: echo "//npm.pkg.github.com/:_authToken=${CIRCLECI_READ_PACKAGES}" >> .npmrc
      - node/install-packages
      - run: npm test

workflows:
  build_test:
    jobs:
      - build_test
