name: Build and test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env:
        GITHUBACTIONS_READ_PACKAGES: ${{ secrets.GITHUBACTIONS_READ_PACKAGES }}
    - run: echo "//npm.pkg.github.com/:_authToken=${GITHUBACTIONS_READ_PACKAGES}" >> .npmrc
    - run: cat .npmrc
    - run: npm ci
    - run: npm test
